### ISSUE TITLE
`riscv`: `interrupt::free()` for Supervisor Mode

### ISSUE THREAD

**Issue by FawazTirmizi** [rust-embedded/riscv#114]
I've noticed that there is no equivalent for `interrupt::free()` for S mode, and I think it is worth adding to this crate. I see two options:

1. Add a new function
2. Put it under a cfg

Are there any opinions on which way to go with this?

**Comment by romancardenas** [comment]
Closing this issue as it is addressed in #165 

Thanks for finding it out!
