### ISSUE TITLE
Replace bors with GitHub merge queues

### ISSUE THREAD

**Issue by romancardenas** [rust-embedded/riscv#133]
As mentioned in the [WG repository](https://github.com/rust-embedded/wg/issues/671), bors is about to stop working. The embedded WG suggested migrating to GitHub merge queues, and this repo could be an excellent candidate to test how this works.

#132 already updates the current CI workflows and is ready to support merge queues. However, we still need to activate the branch protection rule on the repo and, if everything goes well, remove bors. @rust-embedded/riscv are you OK with this?

**Comment by romancardenas** [comment]
Right now, my PR should work for both bors and merge-queue

**Comment by almindor** [comment]
merged + ticked the queue in settings
