### ISSUE TITLE
`riscv-rt`: Implement FPU initialization

### ISSUE THREAD

**Issue by Disasm** [rust-embedded/riscv#157]

**Comment by mini-ninja-64** [comment]
I am happy to have a go at implementing this, what would be the preferred approach for setting FPU as enabled?

a piece of config similar to the m-mode / s-mode switch that the crate currently uses, or something more like if in m-mode use misa config to auto detect FPU presence?

I feel like I read somewhere before misa should be avoided in favour of device tree so maybe it would not make sense to use it for this 🤔 especially as in s-mode we would have to call opensbi or something wierd like that for reading misa and then sstatus for actually setting fs.

**Comment by romancardenas** [comment]
If your target supports the `f` extension, you could use a configuration gate like `#[cfg(riscvf)]` (check [this](https://github.com/rust-embedded/riscv/blob/c579937a17770e26754e448f52e291d511ec99ce/riscv-rt/build.rs#L75)).

We do something similar [here](https://github.com/rust-embedded/riscv/blob/c579937a17770e26754e448f52e291d511ec99ce/riscv-rt/src/asm.rs#L100) for targets supporting integer multiplication.
