### ISSUE TITLE
Why are `asm::fence` and `asm::fence_i` unsafe?

### ISSUE THREAD

**Issue by jsgf** [rust-embedded/riscv#179]
I don't think they can result in any ill-defined states or UB, can they? (Unlike, say, cache invalidation of writeback caches.)

cc @dreiss

**Comment by romancardenas** [comment]
I'm not sure about the reason. Assembly functions were all `unsafe` by default and we've been gradually opting out the `unsafe` token for some of them. Maybe this is the case for `fence` and `fence_i`. Feel free to open a PR :)
