### ISSUE TITLE
`riscv`: align assembly functions with `cortex-m` crate

### ISSUE THREAD

**Issue by romancardenas** [rust-embedded/riscv#181]
Motivated by #179 (and #180), I took a look on how the `cortex-m` crate deals with [assembly instructions](https://github.com/rust-embedded/cortex-m/blob/master/cortex-m/src/asm.rs), and most of them are safe and use options to avoid the compiler from using the stack etc.

@rust-embedded/riscv what do you think about updating our assembly functions to follow the same fashion as in `cortex-m`? @rust-embedded/cortex-m any advice on this?

**Comment by thejpster** [comment]
In general I like it when the risc-v ecosystem kinda looks and feels like the cortex-m ecosystem, as it makes it easier to move between the two.
