### ISSUE TITLE
move plic definition to riscv crate

### ISSUE THREAD

**Issue by dvc94ch** [rust-embedded/riscv#2]

**Comment by dvc94ch** [comment]
Cool stuff! I think we should use this in the riscv crate + add support for using riscv atomics on modify if the a extension is enabled

https://github.com/rust-osdev/register-rs
https://github.com/tock/tock/tree/master/libraries/tock-register-interface

**Comment by Disasm** [comment]
I'm not sure if PLIC definition can be moved here. Looks like PLIC is quite implementation-dependent, so only general super-abstract interface can be described, which is not very useful at first glance.

**Comment by dvc94ch** [comment]
Let's close this for now then...
