### ISSUE TITLE
How to use mcause::read()

### ISSUE THREAD

**Issue by dkhayes117** [rust-embedded/riscv#55]
I've got my Rust code reading the mcause register, but I cannot sprintln! because it doesn't have a core:fmt:binary trait.  How do you match the the mcause contents to the trap enum to get a string?

**Comment by Disasm** [comment]
Probably you need to call `.cause()` to get the `Trap` structure.

**Comment by dkhayes117** [comment]
Still new to Rust modules....I finally realized that all I had to do was `mcause::read().code()` and or `mcause::read().cause()`
