### ISSUE TITLE
Mcounteren Missing

### ISSUE THREAD

**Issue by dkhayes117** [rust-embedded/riscv#56]
I find it strange that the hpmcounterx registers and  time register is implemented but not the mcounteren register.  You cannot use the hpmcounters, time, cycle, or instret without enabling them first in mcounteren.  I probably could submit a pull request for this if needed.

**Comment by Disasm** [comment]
You can't use them in lower privilege mode, yes. Feel free to submit a PR, I'll be glad to review it!

**Comment by dkhayes117** [comment]
This will be my first ever pull request, go easy on me lol.  I've cloned this project into my repo so I can add my changes.  Once I feel like it's close to ready, I will submit the pull request.  Thanks!
