### ISSUE TITLE
RVXXI registers

### ISSUE THREAD

**Issue by Skallwar** [rust-embedded/riscv#60]
Is there a reason why RVXXI registers are not available? If this is just an issue of implementing it, I will gladly do it

![](https://dzone.com/storage/temp/13516052-1590438864710.png)

**Comment by luojia65** [comment]
In my opinion these registers are used by programming code, and operations on common registers should be controlled by compiler or inline assembly only. It's not a common case that we should operate these registers manually.

(In some cases `gp` and `tp` are used when developing OS kernel, but inline assembly should handle with them)

**Comment by romancardenas** [comment]
I agree with @luojia65, these registers are compiler/inline assembly territory. Closing the issue.
